filebeat.modules:
  - module: apache
    access:
      enabled: true
    error:
      enabled: true

filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/apache2/exfiltration.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"
