filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/cron_persistence.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"

processors:
  - add_host_metadata: ~
