filebeat.modules:
  - module: apache
    access:
      enabled: true
      var.paths:
        - /usr/local/apache2/logs/access_log
    error:
      enabled: true
      var.paths:
        - /usr/local/apache2/logs/error_log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"

processors:
  - add_host_metadata: ~
